#!/bin/bash

# downloading SystemC library
wget -O /tmp/systemc.tar.gz http://www.accellera.org/images/downloads/standards/systemc/systemc-2.3.2.tar.gz

# extracting
cd /tmp
mkdir systemc
tar -xzf systemc.tar.gz -C systemc --strip-components=1
cd systemc

# building
mkdir build
cd build
export CXX=g++
../configure CXXFLAGS=-std=c++11 --prefix=/opt/systemc --with-unix-layout --enable-pthreads -q 
make
sudo make install

# cleaning
cd ../../
rm systemc.tar.gz
rm -rf systemc

ln -s -f /opt/systemc/lib/libsystemc-2.3.2.so /usr/lib/libsystemc-2.3.2.so
